'use client';
import React,{createContext,useContext,useState,useEffect,useCallback} from 'react';
import Link from 'next/link';
import {flushSync} from 'react-dom';
import {usePathname} from 'next/navigation';
import {Heart,Search,Menu,X,ArrowUp,ArrowRight,Minus,Plus,Check,Scale} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {products,nav,type Product} from '@/lib/hiyori-data';

type State={favorites:string[];compare:string[];toggleFavorite:(id:string)=>void;toggleCompare:(id:string)=>void;openSaved:()=>void};
const Context=createContext<State>({favorites:[],compare:[],toggleFavorite:()=>{},toggleCompare:()=>{},openSaved:()=>{}});
export const useShop=()=>useContext(Context);
export function Mark({light=false}:{light?:boolean}){return <span className={`wordmark ${light?'light':''}`}><span className="enso" aria-hidden="true"/><span className="mark-kanji">日和</span><span className="mark-kana">ひより</span></span>}
export function ArrowLink({href,children,className=''}:{href:string;children:React.ReactNode;className?:string}){return <Link className={`arrow-link ${className}`} href={href}>{children}<ArrowRight size={17}/></Link>}
export function ProductImage({product,className=''}:{product:Product;className?:string}){return <div role="img" aria-label={`${product.name}のパッケージイメージ`} className={`product-photo ${product.category==='snack'?'snack-photo':''} ${className}`} style={{backgroundImage:`url(${product.image})`,backgroundPosition:`${product.position} ${product.category==='snack'?'65%':'65%'}`}}/>}
export function ProductCard({product}:{product:Product}){const s=useShop();return <article className="product-card"><div className="product-picture"><Link href={`/products/${product.id}`} tabIndex={-1} aria-hidden="true"><ProductImage product={product}/></Link><Button variant="ghost" size="icon" className={`favorite ${s.favorites.includes(product.id)?'chosen':''}`} aria-label={`${product.name}をお気に入り${s.favorites.includes(product.id)?'から削除':'に追加'}`} aria-pressed={s.favorites.includes(product.id)} onClick={()=>s.toggleFavorite(product.id)}><Heart size={19} fill={s.favorites.includes(product.id)?'currentColor':'none'}/></Button><span className="product-status">発売準備中</span></div><div className="product-caption"><span>{product.category==='supplement'?'犬用サプリメント':'犬のおやつ'}</span><Link href={`/products/${product.id}`}><h3>{product.name}</h3></Link><p>{product.note}</p><div className="product-actions"><Link href={`/products/${product.id}`}>詳しく見る <ArrowRight size={14}/></Link><Button variant="ghost" className="compare-button" onClick={()=>s.toggleCompare(product.id)} aria-pressed={s.compare.includes(product.id)}>{s.compare.includes(product.id)?<Check size={13}/>:<Plus size={13}/>} 比較</Button></div></div></article>}
export function SiteShell({children}:{children:React.ReactNode}){
 const pathname=usePathname();const[favorites,setFavorites]=useState<string[]>([]);const[compare,setCompare]=useState<string[]>([]);const[drawer,setDrawer]=useState<'search'|'saved'|'menu'|null>(null);const[query,setQuery]=useState('');const[loaded,setLoaded]=useState(false);const[scrolled,setScrolled]=useState(false);
 useEffect(()=>{try{const f=JSON.parse(localStorage.getItem('hiyori-favorites')||'[]');const c=JSON.parse(localStorage.getItem('hiyori-compare')||'[]');const valid=(x:unknown):x is string=>typeof x==='string'&&products.some(p=>p.id===x);setFavorites(Array.isArray(f)?f.filter(valid):[]);setCompare(Array.isArray(c)?c.filter(valid).slice(0,3):[]);}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('hiyori-favorites',JSON.stringify(favorites));localStorage.setItem('hiyori-compare',JSON.stringify(compare));}catch{}},[favorites,compare,loaded]);
 useEffect(()=>{setDrawer(null)},[pathname]);
 useEffect(()=>{const fn=()=>setScrolled(window.scrollY>260);window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);
 const toggleFavorite=useCallback((id:string)=>{if(!products.some(p=>p.id===id))return;setFavorites(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);},[]);
 const toggleCompare=useCallback((id:string)=>{setCompare(prev=>{if(prev.includes(id))return prev.filter(x=>x!==id);if(prev.length>=3){toast('比較できる商品は３点までです。');return prev;}return [...prev,id]})},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const abort=new AbortController();const register=(tool:any)=>{try{Promise.resolve(ctx.registerTool(tool,{signal:abort.signal})).catch(()=>{})}catch{}};register({name:'search_hiyori_products',title:'日和の商品を探す',description:'公開中の商品情報を検索します。注文は行いません。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(typeof input?.query!=='string')throw Error('検索語を入力してください。');return products.filter(p=>(p.name+p.kana+p.note).includes(input.query)).map(({id,name,note})=>({id,name,note,status:'発売準備中'}))}});register({name:'set_hiyori_favorites',title:'お気に入りを保存する',description:'このブラウザーのお気に入りを指定した商品リストに更新します。注文や予約は行いません。',inputSchema:{type:'object',properties:{productIds:{type:'array',items:{type:'string'}}},required:['productIds'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!Array.isArray(input?.productIds)||input.productIds.some((id:any)=>!products.some(p=>p.id===id)))throw Error('商品が見つかりません。');const ids=[...new Set<string>(input.productIds)];flushSync(()=>setFavorites(ids));return {saved:ids}}});return()=>abort.abort()},[]);
 const results=products.filter(p=>(p.name+p.kana+p.note+(p.category==='snack'?'おやつ':'サプリメント')).includes(query.trim()));
 return <Context.Provider value={{favorites,compare,toggleFavorite,toggleCompare,openSaved:()=>setDrawer('saved')}}><a className="skip-link" href="#main">本文へ進む</a><div className="announcement">健やかな日々を、ともに。<span>五行シリーズ、発売準備中</span></div><header className="site-header"><Link href="/" aria-label="日和 ホーム"><Mark/></Link><nav aria-label="メインナビゲーション">{nav.map(([label,url])=><Link key={url} href={url} className={pathname.startsWith(url)?'active':''}>{label}</Link>)}</nav><div className="header-tools"><Button size="icon" variant="ghost" aria-label="商品を検索" onClick={()=>setDrawer('search')}><Search strokeWidth={1.35}/></Button><Button size="icon" variant="ghost" aria-label={`お気に入り ${favorites.length}件`} onClick={()=>setDrawer('saved')}><Heart strokeWidth={1.35}/>{favorites.length>0&&<sup>{favorites.length}</sup>}</Button><Button className="mobile-menu" size="icon" variant="ghost" aria-label="メニューを開く" onClick={()=>setDrawer('menu')}><Menu strokeWidth={1.35}/></Button></div></header>
 <main id="main">{children}</main>
 <footer className="footer"><div className="footer-main"><div className="footer-brand"><Link href="/" aria-label="日和 ホーム"><Mark light/></Link><p>健やかな日々を、ともに。</p><span>ペットのおやつとサプリメント</span></div><div className="footer-links"><div><h3>日和を知る</h3>{nav.slice(0,3).map(([l,h])=><Link key={h} href={h}>{l}</Link>)}</div><div><h3>日和と暮らす</h3><Link href="/journal">読みもの</Link><Link href="/space">日和の空間</Link><Link href="/news">お知らせ</Link></div><div><h3>ご案内</h3><Link href="/guide">ご利用案内</Link><Link href="/faq">よくあるご質問</Link><Link href="/privacy">プライバシーについて</Link><Link href="/legal">販売について</Link></div></div></div><div className="footer-bottom"><span>© 日和　すべての権利を保有します。</span><span>金　木　水　火　土</span><span>日本語</span></div></footer>
 <Button className={`back-top ${scrolled?'visible':''}`} variant="outline" size="icon" onClick={()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})} aria-label="ページの先頭へ"><ArrowUp size={17}/></Button>
 {compare.length>0&&<div className="compare-bar"><span><Scale size={17}/>比較リスト <b>{compare.length}</b><small>／３点</small></span><Link href="/compare">比較する <ArrowRight size={16}/></Link><Button size="icon" variant="ghost" aria-label="比較リストをクリア" onClick={()=>setCompare([])}><X size={16}/></Button></div>}
 <Sheet open={drawer!==null} onOpenChange={open=>!open&&setDrawer(null)}><SheetContent className="brand-sheet" showCloseButton={false}><SheetClose asChild><Button className="sheet-close" variant="ghost" size="icon" aria-label="閉じる"><X/></Button></SheetClose><SheetTitle className="sheet-title">{drawer==='search'?'商品を探す':drawer==='saved'?'お気に入り':'日和のご案内'}</SheetTitle><SheetDescription>{drawer==='saved'?'このブラウザーに保存した商品です。':drawer==='search'?'シリーズ名や素材の名前で検索できます。':'健やかな日々を、ともに。'}</SheetDescription>
 {drawer==='menu'?<nav className="drawer-nav">{[...nav,['ご利用案内','/guide'],['よくあるご質問','/faq']].map(([l,h])=><Link onClick={()=>setDrawer(null)} key={h} href={h}>{l}<ArrowRight size={16}/></Link>)}</nav>:<><div>{drawer==='search'&&<><label htmlFor="search-products" className="sr-only">商品名・シリーズ名</label><Input id="search-products" className="search-input" placeholder="金、木、ささみなど" value={query} onChange={e=>setQuery(e.target.value)}/><p className="small search-count">{results.length}件の商品</p></>}</div><div className="drawer-products">{(drawer==='search'?results:products.filter(p=>favorites.includes(p.id))).map(p=><div className="drawer-product" key={p.id}><Link href={`/products/${p.id}`} onClick={()=>setDrawer(null)}><ProductImage product={p}/></Link><div><span className="small">{p.note}</span><Link href={`/products/${p.id}`} onClick={()=>setDrawer(null)}>{p.name}</Link><span className="small">発売準備中</span></div>{drawer==='saved'&&<Button variant="ghost" size="icon" aria-label={`${p.name}を削除`} onClick={()=>toggleFavorite(p.id)}><X size={16}/></Button>}</div>)}{(drawer==='search'?results.length===0:favorites.length===0)&&<div className="empty-state"><Heart strokeWidth={1}/><h3>{drawer==='search'?'商品が見つかりませんでした。':'気になるひと品を、ここに。'}</h3><p>{drawer==='search'?'別の言葉でお試しください。':'商品についているハートを押すと、ここに保存されます。'}</p><ArrowLink href="/collections">五行シリーズを見る</ArrowLink></div>}</div></>}
 </SheetContent></Sheet><Toaster position="bottom-center" theme="light" toastOptions={{className:'japanese-toast'}}/></Context.Provider>
}
